# Generated by Django 5.2.3 on 2025-06-28 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(auto_created=True, default=uuid.UUID('4c2afcba-5e1a-43be-9836-013174929aec'), editable=False, unique=True)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tel', models.CharField(max_length=25)),
                ('tel2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pays', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ville', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('addresse', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
