# Generated by Django 5.2.3 on 2025-07-02 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('98db6855-1fea-4554-af10-2bea2747c2df'), editable=False, unique=True),
        ),
    ]
