# Generated by Django 5.2.3 on 2025-07-10 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('b70029ea-6b95-427d-8d2c-cb7d9dbda6ce'), editable=False, unique=True),
        ),
    ]
