# Generated by Django 5.2.3 on 2025-08-19 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('84b7f4a9-5332-47d2-bdb6-8183c76fee2e'), editable=False, unique=True),
        ),
    ]
