# Generated by Django 5.2.3 on 2025-09-13 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('0b8b48e7-2e87-4130-aacc-ad5058857ac0'), editable=False, unique=True),
        ),
    ]
