# Generated by Django 5.2.3 on 2025-09-15 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('fd866bf8-8dbf-4538-9a2d-da93cfea3b89'), editable=False, unique=True),
        ),
    ]
