# Generated by Django 5.2.3 on 2025-09-15 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('5f79f554-5056-46fb-b8e4-ef8b73110958'), editable=False, unique=True),
        ),
    ]
