# Generated by Django 5.2.3 on 2025-09-15 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('b55e3b64-deb2-4e98-b295-5f7f36351965'), editable=False, unique=True),
        ),
    ]
