# Generated by Django 5.2.3 on 2025-09-15 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0008_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('7f491fb3-d469-424b-b4c9-4735bfeea1c2'), editable=False, unique=True),
        ),
    ]
