# Generated by Django 5.2.3 on 2025-09-15 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0009_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('45ea89ac-cd5f-411f-8a71-1fb9d630608e'), editable=False, unique=True),
        ),
    ]
