# Generated by Django 5.2.3 on 2025-09-24 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0010_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('2189bdc1-19e5-44dc-b08d-4c52190903cc'), editable=False, unique=True),
        ),
    ]
