# Generated by Django 5.2.3 on 2025-09-29 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0011_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('74757dd5-695d-46db-b2b7-057ec918c0d3'), editable=False, unique=True),
        ),
    ]
