# Generated by Django 5.2.3 on 2025-10-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0013_alter_profile_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du logo (ex: Logo principal)', max_length=100)),
                ('image', models.ImageField(help_text='Image du logo (formats: PNG, JPG, SVG)', upload_to='logos/')),
                ('est_actif', models.BooleanField(default=False, help_text='Logo actuellement utilisé dans la navbar')),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du logo', null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
                'ordering': ['-date_modification'],
            },
        ),
    ]
