# Generated by Django 5.2.3 on 2025-10-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_date_execution_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_execution',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
