# Generated by Django 5.2.3 on 2025-07-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0003_alter_profile_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('FCFA', 'FCFA'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('INR', 'INR'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF')], default='FCFA', help_text='Currency type for the budget sheet', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_budget_sheets', to='customuser.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TypeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_due_date', models.BooleanField(default=False, help_text='Indicates if the budget has an expiration date')),
                ('is_date_created', models.BooleanField(default=False, help_text='Indicates if the budget has a creation date')),
                ('is_compte', models.BooleanField(default=False, help_text='Indicates if the budget is a compte type')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type_budgets', to='customuser.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_reel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, help_text='Expiration date of the budget', null=True)),
                ('is_date_created', models.DateField(blank=True, help_text='Creation date of the budget', null=True)),
                ('account', models.CharField(blank=True, help_text='Account associated with the budget', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_budgets', to='customuser.profile')),
                ('type_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='gestionbuget.typebudget')),
            ],
        ),
    ]
