# Generated by Django 5.2.3 on 2025-07-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsheet',
            name='pid',
            field=models.CharField(default=1, help_text='Unique identifier for the budget sheet', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
