# Generated by Django 5.2.3 on 2025-07-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0002_budgetsheet_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='type_budget',
        ),
        migrations.AlterField(
            model_name='budgetsheet',
            name='currency',
            field=models.CharField(choices=[('FCFA', 'FCFA'), ('USD', '$'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('INR', 'INR'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF')], default='FCFA', help_text='Currency type for the budget sheet', max_length=10),
        ),
        migrations.AlterField(
            model_name='typebudget',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
