# Generated by Django 5.2.3 on 2025-07-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0003_remove_budget_type_budget_alter_budgetsheet_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='type_budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='gestionbuget.typebudget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typebudget',
            name='budget_sheet',
            field=models.ForeignKey(default=122223, on_delete=django.db.models.deletion.CASCADE, related_name='type_budgets_sheet', to='gestionbuget.budgetsheet'),
            preserve_default=False,
        ),
    ]
