# Generated by Django 5.2.3 on 2025-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0004_budget_type_budget_typebudget_budget_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebudget',
            name='is_salary',
            field=models.BooleanField(default=False, help_text='Indicates if the budget is a salary type'),
        ),
    ]
