# Generated by Django 5.2.3 on 2025-07-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0005_typebudget_is_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebudget',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budgetsheet',
            name='currency',
            field=models.CharField(choices=[('FCFA', 'FCFA'), ('USD', '$'), ('EUR', '€'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('INR', 'INR'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF')], default='FCFA', help_text='Currency type for the budget sheet', max_length=10),
        ),
    ]
