# Generated by Django 5.2.3 on 2025-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0006_typebudget_is_income_alter_budgetsheet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='pid',
            field=models.CharField(default=11, help_text='Unique identifier for the budget sheet', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
