# Generated by Django 5.2.3 on 2025-07-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0007_budget_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount_reel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount_spent',
            field=models.IntegerField(default=0),
        ),
    ]
