# Generated by Django 5.2.3 on 2025-07-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0008_alter_budget_amount_reel_alter_budget_amount_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount_reel',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
