# Generated by Django 5.2.3 on 2025-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0009_alter_budget_amount_reel_alter_budget_amount_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebudget',
            name='is_spent',
            field=models.BooleanField(default=False),
        ),
    ]
