# Generated by Django 5.2.3 on 2025-08-19 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_alter_profile_pid'),
        ('gestionbuget', '0010_typebudget_is_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(help_text='Unique identifier for the budget sheet', max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_reel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='doc/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demanse_budgets_sheet', to='gestionbuget.budgetsheet')),
                ('type_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='gestionbuget.typebudget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_demande', to='customuser.profile')),
                ('user_validete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_validate', to='customuser.profile')),
            ],
        ),
    ]
