# Generated by Django 5.2.3 on 2025-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0011_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=15),
        ),
    ]
