# Generated by Django 5.2.3 on 2025-09-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_alter_profile_pid'),
        ('gestionbuget', '0012_demande_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='file_reel',
            field=models.FileField(blank=True, null=True, upload_to='doc/'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='amount_reel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CommentDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_comment', to='gestionbuget.demande')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_demande', to='customuser.profile')),
            ],
        ),
    ]
