# Generated by Django 5.2.3 on 2025-09-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_alter_profile_pid'),
        ('gestionbuget', '0013_demande_file_reel_alter_demande_amount_reel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetPartener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(help_text='Unique identifier partener', max_length=24, unique=True)),
                ('role', models.CharField(choices=[('superadmin', 'SuperAdmin'), ('gerant', 'Gérant'), ('gestionnaire', 'gestionaire'), ('consultation', 'Consultation')], default='consultation', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_partener_sheet', to='customuser.profile')),
            ],
        ),
    ]
