# Generated by Django 5.2.3 on 2025-09-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0014_sheetpartener'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsheet',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
