# Generated by Django 5.2.3 on 2025-09-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0015_budgetsheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetpartener',
            name='sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_sheet_partenaire', to='gestionbuget.budgetsheet'),
            preserve_default=False,
        ),
    ]
