# Generated by Django 5.2.3 on 2025-09-15 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0016_sheetpartener_sheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetsheet',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='demande',
            name='user_validete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_validate', to='gestionbuget.sheetpartener'),
        ),
    ]
