# Generated by Django 5.2.3 on 2025-10-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0013_alter_profile_pid'),
        ('gestionbuget', '0017_alter_budgetsheet_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=24, unique=True)),
                ('email_or_username', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('superadmin', 'SuperAdmin'), ('gerant', 'Gérant'), ('gestionnaire', 'gestionaire'), ('consultation', 'Consultation')], default='consultation', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('expired', 'Expirée')], default='pending', max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='customuser.profile')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='gestionbuget.budgetsheet')),
            ],
        ),
    ]
