# Generated by Django 5.2.3 on 2025-10-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0018_sheetinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetinvitation',
            name='role',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('gestionnaire', 'Gestionnaire'), ('gerant', 'Gérant'), ('superadmin', 'SuperAdmin')], default='consultation', max_length=50),
        ),
        migrations.AlterField(
            model_name='sheetpartener',
            name='role',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('gestionnaire', 'Gestionnaire'), ('gerant', 'Gérant'), ('superadmin', 'SuperAdmin')], default='consultation', max_length=50),
        ),
    ]
