# Generated by Django 5.2.3 on 2025-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbuget', '0019_alter_sheetinvitation_role_alter_sheetpartener_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typebudget',
            name='is_salary',
        ),
        migrations.AddField(
            model_name='typebudget',
            name='is_saving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typebudget',
            name='is_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
