# Generated by Django 5.2.3 on 2025-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('type_champs', models.CharField(choices=[('charField', 'Champ de type texte'), ('textField', 'Champ de type texte long'), ('integerField', 'Champ de type entier'), ('dateField', 'Champ de type date'), ('booleanField', 'Champ de type booléen'), ('emailField', 'Champ de type email'), ('fileField', 'Champ de type fichier'), ('imageField', 'Champ de type image'), ('urlField', 'Champ de type URL'), ('floatField', 'Champ de type nombre à virgule flottante'), ('decimalField', 'Champ de type nombre décimal'), ('timeField', 'Champ de type heure'), ('dateTimeField', 'Champ de type date et heure'), ('foreignKey', 'Champ de type clé étrangère'), ('manyToManyField', 'Champ de type plusieurs à plusieurs'), ('oneToOneField', 'Champ de type un à un')], default='charField', max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champs', models.ManyToManyField(blank=True, to='lawyer.champs')),
            ],
        ),
    ]
