# Generated by Django 5.2.3 on 2025-09-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeactivity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
