# Generated by Django 5.2.3 on 2025-10-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0013_alter_profile_pid'),
        ('gestionbuget', '0017_alter_budgetsheet_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(help_text='Identifiant unique du résumé', max_length=100, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(help_text='Décrivez les activités et réalisations de la journée', verbose_name='Contenu du résumé')),
                ('date_resume', models.DateField(help_text='Date de la journée résumée', verbose_name='Date du résumé')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes_authored', to='customuser.profile', verbose_name='Auteur')),
                ('budget_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='gestionbuget.budgetsheet', verbose_name='Feuille de budget')),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes_received', to='customuser.profile', verbose_name='Destinataire (supérieur)')),
            ],
            options={
                'verbose_name': 'Résumé journalier',
                'verbose_name_plural': 'Résumés journaliers',
                'ordering': ['-date_resume', '-created_at'],
                'unique_together': {('author', 'budget_sheet', 'date_resume')},
            },
        ),
        migrations.CreateModel(
            name='CommentResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_comments', to='customuser.profile', verbose_name='Auteur du commentaire')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resume.resume', verbose_name='Résumé')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hierarchie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchies', to='gestionbuget.budgetsheet', verbose_name='Feuille de budget')),
                ('superieur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to='customuser.profile', verbose_name='Supérieur hiérarchique')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchie', to='customuser.profile', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Hiérarchie',
                'verbose_name_plural': 'Hiérarchies',
                'ordering': ['budget_sheet', 'user'],
                'unique_together': {('user', 'budget_sheet')},
            },
        ),
    ]
