# Generated by Django 5.2.3 on 2025-10-04 15:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-date_resume', '-created_at'], 'verbose_name': 'Rapport journalier', 'verbose_name_plural': 'Rapports journaliers'},
        ),
        migrations.AlterField(
            model_name='commentresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resume.resume', verbose_name='Rapport'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Décrivez les activités et réalisations de la journée', verbose_name='Contenu du rapport'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_resume',
            field=models.DateField(help_text='Date de la journée rapportée', verbose_name='Date du rapport'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pid',
            field=models.CharField(help_text='Identifiant unique du rapport', max_length=100, unique=True),
        ),
    ]
